name: e2e tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start App
        run: |
          yarn
          yarn start

      - uses: cypress-io/github-action@v2
        with:
          wait-on: "http://localhost:8081"
          working-directory: e2e
